# Travis-CI Build for Cronos
# see travis-ci.org for details

sudo: required
dist: trusty

language: cpp

os: 
  - linux
  - osx
  
env:  
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - CLI_VERSION=1.0.0-rc4-004771

before_install:  
  - if test "$TRAVIS_OS_NAME" == "osx"; 
    then 
        brew update;
        brew install openssl --force;
        mkdir -p /usr/local/lib;
        ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/;
        ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/;
        export DOTNET_INSTALL_DIR="$PWD/.dotnetcli";
        export PATH="$DOTNET_INSTALL_DIR:$PATH";
        travis_retry curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR";
    else
        sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list';
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893;
        sudo apt-get update;
        sudo apt-get install "dotnet-dev-$CLI_VERSION";
    fi

# Run the build script
script:
    travis_retry dotnet restore Cronos.sln --disable-parallel;
    dotnet test tests/Cronos.Tests/Cronos.Tests.csproj -c:Release -f:netcoreapp1.0;
  
  

