# AppVeyor CI build file, https://ci.appveyor.com/project/odinserj/cronos

# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.
os: Visual Studio 2017 RC

cache:
  - packages

  # branches to build
branches:
  # whitelist
  only:
    - master
    - dev

pull_requests:
  do_not_increment_build_number: true
  
#---------------------------------#
#       build configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic MSBuild
build_script:
  - powershell .\build.ps1
  
#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'build\*.nupkg'
  - path: 'build\*.zip'

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy:
  - provider: GitHub
    auth_token:
      secure: Hw+eMEw//BNM8ZZSQidchwbrj25XFKykj+NdQKXtXWEsHKZdXTWRZjfDjK6UZLxU
    artifact: /.*\.zip/
    draft: true
    on:
      appveyor_repo_tag: true

  - provider: NuGet
    api_key: 
      secure: P7SfXBeFQixVqdEFlyFtRb39IytB+/RijG46obop/pv64uBk7uEba4p4oNZOvHde
    on:
      appveyor_repo_tag: true